version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: homesweet-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: homesweet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - homesweet-network

  redis:
    image: redis:7.2
    container_name: homesweet-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - homesweet-network

    ### Kafka (단일)
  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"   # 외부(Spring Boot) 접근
  #     - "29092:29092"
  #   environment:
  #     # 카프카 기본 설정 / Krafkt
  #     CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  #     KAFKA_BROKER_ID: 1

  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_NODE_ID: 1
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

  #     # 로그
  #     KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  #     # 토픽
  #     KAFKA_NUM_PARTITIONS: 3
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  #     # 리스너 설정
  #     KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      
  #   volumes:
  #     - kafka-data:/var/lib/kafka/data
  #   networks:
  #     - homesweet-network

  ### Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8989:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=homesweet-kafka-ec2
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=16.184.63.204:9092
    networks:
      - homesweet-network

networks:
  homesweet-network:
    driver: bridge

volumes:
  mysqldata:
  redisdata:  
  kafka-data: