version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: homesweet-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: homesweet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - homesweet-network

  redis:
    image: redis:7.2
    container_name: homesweet-redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - homesweet-network

networks:
  homesweet-network:
    driver: bridge

volumes:
  mysqldata:
  redisdata: